"""
Teste
DAG auto-generated by Astro Cloud IDE.
"""
from airflow.decorators import dag, task
from datetime import datetime

@task
def hello_world():
    print("Hello World - Testando ...")

@dag(
    dag_id='hello_world',
    start_date=datetime(2025, 9, 15),
    schedule='@daily',
    catchup=False,
    default_args={'retries': 1},
)
def hello_world_dag():
    hello_world_task = hello_world()




dag = hello_world_dag()





